tiktok_url: "https://www.tiktok.com/@lachmood"
youtube_url: "https://www.youtube.com/@lachmood"
instagram_url: "https://www.instagram.com/lachmood/"
twitter_url: "https://twitter.com/lachcontent"
twitch_url: "https://www.twitch.tv/lachmood"